apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: igor-eks-demo
  region: eu-west-1
  version: "1.21"

vpc:
  cidr: 10.68.0.0/16
  nat:
    gateway: Single

# nodeGroups:
# - name: ng-spot-1
#   minSize: 2
#   maxSize: 10
#   labels:
#     nodegroup-type: spot
#   tags:
#     nodegroup-type: spot
#   privateNetworking: true
#   volumeSize: 25
#   instancesDistribution:
#     maxPrice: 0.017
#     instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
#     onDemandBaseCapacity: 0
#     onDemandPercentageAboveBaseCapacity: 0
#     spotInstancePools: 2
#   ssh:
#     publicKeyName: "IrDevProduct-2017"
#   iam:
#     withAddonPolicies:
#       imageBuilder: true
#       autoScaler: true
#       externalDNS: true
#       certManager: true
#       appMesh: true
#       ebs: true
#       fsx: true
#       efs: true
#       albIngress: true
#       xRay: true
#       cloudWatch: true

managedNodeGroups:
- name: ng-spot-managed-1
  minSize: 2
  maxSize: 10
  labels:
    nodegroup-type: spot
    managed: "true"
  tags:
    nodegroup-type: spot
    managed: "true"
  privateNetworking: true
  volumeSize: 25
  spot: true
  instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
  ssh:
    publicKeyName: "IrDevProduct-2017"
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      xRay: true
      cloudWatch: true

# fargateProfiles:
#   - name: fp-dev
#     selectors:
#       # All workloads in the "dev" Kubernetes namespace matching the following
#       # label selectors will be scheduled onto Fargate:
#       - namespace: earnix-demo
#         labels:
#           env: dev
#     tags:
#       env: dev
#       name: fp-dev
#   - name: fp-dev-2
#     selectors:
#       # All workloads in the "dev" Kubernetes namespace matching the following
#       # label selectors will be scheduled onto Fargate:
#       - namespace: earnix-demo-2
#         labels:
#           env: dev
#     tags:
#       env: dev
#       name: fp-dev-2
    