---
apiVersion: v1
kind: Namespace
metadata:
  name: earnix-demo
  labels:
    env: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: earnix-demo
  name: deployment-2048
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
      env: dev
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
        env: dev
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: earnix-demo
  name: service-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048
    env: dev
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: earnix-demo
  name: ingress-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-2048
              servicePort: 80
